hotfix: change workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -42,6 +42,16 @@ jobs:
       - name: Build Application
         run: npm run build
 
+      - name: Check dist folder contents
+        run: ls -la dist
+
+      - name: Check mockServiceWorker.js
+        run: |
+          if [ ! -f "dist/mockServiceWorker.js" ]; then
+            echo "Error: mockServiceWorker.js not found in dist folder."
+            exit 1
+          fi
+
       #Публикуем приложение на Github Pages
       - name: Deploy to Github Pages
         uses: JamesIves/github-pages-deploy-action@4.2.1
